###
POST http://127.0.0.1:8000/api/v1/auth/signup/
Content-Type: application/json

{
    "email": "bfffv@assaf.sf",
    "username": "fssg",
    "role": "admin"
}


###
POST http://127.0.0.1:8000/api/v1/auth/token/
Content-Type: application/json

{
    "username": "fsdfsdfsads3qa",
    "confirmation_code": "88775"
}

###
GET http://127.0.0.1:8000/api/v1/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjYwMzMyMzAzLCJqdGkiOiIyZGY1M2JlYzFlMWU0N2U3ODg4NmExZTVmMTFhMDI4MSIsInVzZXJfaWQiOjM4fQ.14K8JLxS9QFqLfMnv0t1DgOvscxsJjpt7s-2Fgguoew