###
POST http://127.0.0.1:8000/auth/users/
Content-Type: application/json

{
    "email": "Pop@jffsf.sf",
    "username": "pjop",
    "password": "Possssssf"
}

###
GET 
Content-Type: application/json
Authorization: Token 