# Generated by Django 2.2.16 on 2022-08-10 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220810_2101'),
        ('users', '0008_auto_20220810_1950'),
    ]

    operations = [
    ]
