# Generated by Django 2.2.16 on 2022-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20220811_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='00A00', max_length=5),
        ),
    ]
