# Generated by Django 2.2.16 on 2022-08-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20220810_2330'),
        ('users', '0012_user_confirmation_code'),
    ]

    operations = [
    ]
