# Generated by Django 2.2.16 on 2022-08-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20220811_2026'),
        ('users', '0014_auto_20220812_1642'),
    ]

    operations = [
    ]
