# Generated by Django 2.2.16 on 2022-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20220812_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
