# Generated by Django 2.2.16 on 2022-08-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20220812_1644'),
        ('users', '0016_auto_20220812_1950'),
    ]

    operations = [
    ]
