# Generated by Django 2.2.16 on 2022-08-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_merge_20220813_1033'),
        ('users', '0014_auto_20220811_2258'),
    ]

    operations = [
    ]
