# Generated by Django 2.2.16 on 2022-08-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220813_1443'),
        ('users', '0020_auto_20220813_1129'),
    ]

    operations = [
    ]
