# Generated by Django 2.2.16 on 2022-08-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20220813_1209'),
        ('users', '0022_auto_20220814_1041'),
    ]

    operations = [
    ]
