# Generated by Django 2.2.16 on 2022-08-13 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220813_1302'),
        ('reviews', '0002_comment_review'),
    ]

    operations = [
    ]
