# Generated by Django 2.2.16 on 2022-08-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_merge_20220813_1449'),
        ('reviews', '0003_review_score'),
    ]

    operations = [
    ]
