# Generated by Django 2.2.16 on 2022-08-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_auto_20220815_0835'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_booking',
        ),
    ]
