# Generated by Django 2.2.16 on 2022-08-14 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_title_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
    ]
