# Generated by Django 2.2.16 on 2022-08-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_auto_20220816_1850'),
        ('reviews', '0013_remove_title_rating'),
    ]

    operations = [
    ]
