# Generated by Django 2.2.16 on 2022-08-17 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_merge_20220817_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'баллы должны быть в диапазоне от 1 до 10'), django.core.validators.MaxValueValidator(10, 'баллы должны быть в диапазоне от 1 до 10')]),
        ),
    ]
